---
title: "Yelp"
author: "Xiang Zhao"
date: "11/27/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,warning=FALSE}
#install.packages("RMySQL")  # If you don't have this package, you may have to install first.
library(RMySQL)
library(dplyr)
library(tidyr)
```

```{r}
#Read data from sql.
mydb = dbConnect(MySQL(), user='mssp', password='mssp2017', dbname='yelp_db', host='45.63.90.29')
user.sql <- dbSendQuery(mydb, "select * from user")
user = fetch(user.sql, n = -1)

business.sql <- dbSendQuery(mydb, "select * from business")
business = fetch(business.sql, n = -1)

attribute.sql <- dbSendQuery(mydb, "select * from attribute")
attribute = fetch(attribute.sql, n = -1)

category.sql <- dbSendQuery(mydb, "select * from category")
category = fetch(category.sql, n = -1)

review.sql <- dbSendQuery(mydb, "select business_id,user_id,stars from review")
review = fetch(review.sql, n = -1)
```

```{r}
#Extract attributes for modeling.
wifi <- attribute%>%
  filter(name == "WiFi")

price <- attribute%>%
  filter(name == "RestaurantsPriceRange2")

parking <- attribute%>%
  filter(name == "BusinessParking")

noise <- attribute%>%
  filter(name == "NoiseLevel")

TV <- attribute%>%
  filter(name == "HasTV")

outdoor <- attribute%>%
  filter(name == "OutdoorSeating")
#Join several datasets of different attributes.
attribute6 <- left_join(wifi,price,by = "business_id")
attribute6 <- left_join(attribute6,parking, by = "business_id")
attribute6 <- left_join(attribute6,noise, by = "business_id")
attribute6 <- left_join(attribute6,TV, by = "business_id")
attribute6 <- left_join(attribute6,outdoor, by = "business_id")
#Rename the columns' names.
colnames(attribute6)[3] <- "WiFi"
colnames(attribute6)[5] <- "Price Range"
colnames(attribute6)[7] <- "Parking"
colnames(attribute6)[9] <- "Noise Level"
colnames(attribute6)[11] <- "TV"
colnames(attribute6)[13] <- "Outdoor Seating"
#Refine the whole one dataset of attributes.
attribute6 <- cbind(attribute6[1],attribute6[3],attribute6[5],attribute6[7],attribute6[9],attribute6[11],attribute6[13])
attribute6 <- na.omit(attribute6)

```

```{r}
#Filter the restaurants of all the stores in 'business' dataset. 
restaurants_filter <- category%>%
  filter(category == "Restaurants")
#Join the restaurants with the style of each restaurant.
restaurants_type <- left_join(restaurants_filter, category, by = "business_id")
#Check the number of each style 
#restaurants_type%>%
#  count(category.y)%>%
#  arrange(desc(n))
#Filter the style of each restaurant.
restaurants_type.new <- restaurants_type%>%
  select(business_id,category.x,category.y)%>%
  filter(category.y == "Japanese"|category.y == "Chinese"|category.y == "Thai"|category.y == "Korean"|category.y == "Vietnamese"|category.y == "Indian")
#Join the style of restaurants with restaurants' informations.
colnames(business)[1] <- "business_id"
restaurants <- left_join(restaurants_type.new,business, by = "business_id")
#Clean the NA.
restaurants_attribute6.na <- left_join(restaurants,attribute6, by = "business_id")
restaurants_attribute6 <- na.omit(restaurants_attribute6.na)
#Delete the useless columns.
restaurants_attribute6$category.x <- NULL
restaurants_attribute6$category <- NULL
restaurants_attribute6$neighborhood <- NULL
restaurants_attribute6$address <- NULL
restaurants_attribute6$postal_code <- NULL
restaurants_attribute6$latitude <- NULL
restaurants_attribute6$longitude <- NULL

#Change the column's name.
colnames(restaurants_attribute6)[2] <- "restaurant_style"

#Choose only one of several styles one restaurant may have.
restaurants_attribute6 <- restaurants_attribute6[!duplicated(restaurants_attribute6$business_id, fromLast = T),]
#Choose the restaurants open now.
restaurants_attribute6 <- restaurants_attribute6%>%
  select(everything())%>%
  filter(is_open == 1)
#Check the number of style of each restaurant.
#restaurants_attribute6%>%
#  count(restaurant_style)%>%
#  arrange(desc(n))
#Combine the 'Indian'&'Thai'&'Vietnamese' into 'Southeast Asian'
restaurants_attribute6$restaurant_style <- as.character(restaurants_attribute6$restaurant_style)
restaurants_attribute6$restaurant_style[restaurants_attribute6$restaurant_style == "Indian"] <- "Southeast Asian"
restaurants_attribute6$restaurant_style[restaurants_attribute6$restaurant_style == "Thai"] <- "Southeast Asian"
restaurants_attribute6$restaurant_style[restaurants_attribute6$restaurant_style == "Vietnamese"] <- "Southeast Asian"
#Check again.
#restaurants_attribute6%>%
#  count(restaurant_style)%>%
#  arrange(desc(n))
#Delete the column for 'is.open'
restaurants_attribute6 <- restaurants_attribute6[,-8]
```

```{r}
#Parse parking
#Divide the parking columns.
restaurants_attribute6 <- separate(data = restaurants_attribute6 ,col = Parking, into = c("garage","street","validated","lot","valet"), sep = '\\,',remove = T)
#Set 'garage' to the correct format.
restaurants_attribute6 <- separate(data = restaurants_attribute6 ,col = garage, into = c("type_garage","garage"), sep = '\\:',remove = T)
#Set 'street' to the correct format.
restaurants_attribute6 <- separate(data = restaurants_attribute6 ,col = street, into = c("type_street","street"), sep = '\\:',remove = T)
#Set 'validated' to the correct format.
restaurants_attribute6 <- separate(data = restaurants_attribute6 ,col = validated, into = c("type_validated","validated"), sep = '\\:',remove = T)
#Set 'lot' to the correct format.
restaurants_attribute6 <- separate(data = restaurants_attribute6 ,col = lot, into = c("type_lot","lot"), sep = '\\:',remove = T)
#Set 'valet' to the correct format.
restaurants_attribute6 <- separate(data = restaurants_attribute6 ,col = valet, into = c("type_valet","valet"), sep = '\\:',remove = T)
#Clean punctuations.
restaurants_attribute6 <- separate(data = restaurants_attribute6 ,col = valet, into = c("valet","null"), sep = '\\}',remove = T)
#Delete useless columns.
restaurants_attribute6$type_garage <- NULL
restaurants_attribute6$type_street <- NULL
restaurants_attribute6$type_validated <- NULL
restaurants_attribute6$type_lot <- NULL
restaurants_attribute6$type_valet <- NULL
restaurants_attribute6$null <- NULL
#Clean all the NAs.
restaurants_attribute6 <- na.omit(restaurants_attribute6)
#Rename the dataset.
colnames(restaurants_attribute6) <- c("business_id", "restaurant_style", "restaurant_name", "restaurant_city", "restaurant_state", "restaurant_stars", "restaurant_review_count", "restaurant_WiFi", "restaurant_price_range", "garage_parking","street_parking","validated_parking","lot_parking","valet_parking","restaurant_noise_level", "restaurant_TV", "restaurant_outdoor_seating")
```

```{r}
#Set dataset for users.
user.new <- data.frame(cbind(user$id,user$name,user$review_count,user$average_stars))
#Rename the dataset.
colnames(user.new) <- c("user_id","name","review_count","average_stars")
#Join the datasets of users and reviews.
user_review <- left_join(review,user.new,by = "user_id")
```

```{r}
#Join the datasets of restaurants and users.
restaurants_users <- left_join(restaurants_attribute6,user_review,by = "business_id")
#Clean all the NAs.
restaurants_users <- na.omit(restaurants_users)
#Rename the dataset.
colnames(restaurants_users) <- c("business_id", "restaurant_style", "restaurant_name", "restaurant_city", "restaurant_state", "restaurant_stars", "restaurant_review_count", "restaurant_WiFi", "restaurant_price_range", "garage_parking","street_parking","validated_parking","lot_parking","valet_parking","restaurant_noise_level", "restaurant_TV", "restaurant_outdoor_seating", "user_id", "user_stars", "user_name", "user_review_count", "user_average_stars")

```

```{r}
#Save the dataset in RDS file
saveRDS(restaurants_users,"restaurants_users.rds")
##Save the dataset in DTA file
save(restaurants_users,file = "restaurants_users.RData")
```